
" call pathogen#runtime_append_all_bundles()

" To Do: understand
" - quickrun, unite.vim, neocomplcache, vimshell
" - AtokX http://vim-users.jp/2009/09/hack79/


filetype off
filetype plugin indent off
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
  call neobundle#rc(expand('~/.vim/bundle/'))
endif

NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/vimshell'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'tpope/vim-surround'
NeoBundle 'mattn/zencoding-vim'
NeoBundle 'eagletmt/ghcmod-vim'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'ingydotnet/yaml-vim'
NeoBundle 'mattn/calendar-vim'
NeoBundle 'thinca/vim-quickrun'
NeoBundle 'thinca/vim-ft-clojure'
" thinca/vim-quickrun'
" NeoBundle 'kana/vim-metarw'
" NeoBundle 'ujihisa/neco-ghc/'

filetype plugin indent on
filetype on
set nocompatible


" クリップボードから貼り付け
" inoremap <C-r>* <C-o>:set paste<CR><C-r>*<C-o>:set nopaste<CR>

set expandtab
set softtabstop=4
set shiftwidth=4
set showmatch
set smarttab
set smartindent
set tabstop=4
set backup
set autoindent
set smartcase
set wrap
syntax enable
colorscheme evening

set splitbelow
set splitright
set title
set nohidden

"it shows statusline some thing like:"
"[utf-8 unix vim tab=4]~/.vim/rc/vimrc    [+]   line=54/60,92%"
set statusline=[%{&fileencoding}\ %{&fileformat}\ %{&filetype}\ tab=%{&tabstop}]%F%9(\ %m%r\ %)%=line=%l/%L,%P
set laststatus=1
set cmdheight=1

set encoding=utf-8
set termencoding=utf-8
"support vim: in file to open. i.e.
"vim: set expandtab fenc=cp932 ff=unix ft=txt : # この行はvimエディタのモードラインです。
set modeline



" NeoBundle 'Shougo/neocomplcache'
let g:neocomplcache_enable_at_startup = 1



