
call pathogen#runtime_append_all_bundles()


filetype off
filetype plugin indent off
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
  call neobundle#rc(expand('~/.vim/bundle/'))
endif

NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/vimshell'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'tpope/vim-surround'


filetype plugin indent on

set expandtab
set softtabstop=2
set shiftwidth=2
set showmatch
set smarttab
set smartindent
set tabstop=2
set backup
set autoindent
set smartcase
syntax enable
colorscheme evening

set splitbelow
set splitright
set title

set modeline
set laststatus=3
set statusline=%F%r%h%=
set cmdheight=3

set encoding=utf-8
set termencoding=utf-8

