
call pathogen#runtime_append_all_bundles()


filetype off
filetype plugin indent off
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
  call neobundle#rc(expand('~/.vim/bundle/'))
endif

NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/vimshell'
NeoBundle 'tpope/vim-surround'
NeoBundle 'mattn/zencoding-vim'
NeoBundle 'eagletmt/ghcmod-vim'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'ingydotnet/yaml-vim'
NeoBundle 'mattn/calendar-vim'

filetype plugin indent on

set expandtab
set softtabstop=4
set shiftwidth=4
set showmatch
set smarttab
set smartindent
set tabstop=4
set backup
set autoindent
set smartcase
syntax enable
colorscheme evening

set splitbelow
set splitright
set title

set modeline
set laststatus=1
set statusline=%F%r%h%=
set cmdheight=1

set encoding=utf-8
set termencoding=utf-8

